[package]
name = "nd-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tokio.workspace = true
notify.workspace = true
thiserror.workspace = true
tempfile.workspace = true
fs2.workspace = true

[lints]
workspace = true
