[package]
name = "nd-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gpui-kit.workspace = true
nd-view-model.workspace = true
nd-ui-core.workspace = true
nd-wire.workspace = true
tokio.workspace = true
serde_json.workspace = true

[lints]
workspace = true

[features]
scenarios = []
